export { default as Welcome } from "./Welcome"
export { default as Home } from "./Home"
export { default as Error } from "./Error"
export { default as Inbox } from "./Inbox"
export { default as Profile } from "./Profile"
export { default as Artist } from "./Artist"
export { default as Album } from "./Album"